- name: Get all VMs within resource group and power off
  hosts: localhost
  connection: local
  tasks:
  - name: Get all VMs within resource group
    azure_rm_virtualmachine_info:
      name: k8s-rg
    register: vms
  - name: Power Off all VMs
    azure_rm_virtualmachine:
      resource_group: k8s-rg
      name: "{{ item }}"
      started: no
    loop: "{{ vms.resources | map(attribute='name') }}"